version: '3.3'
services:
    stirling-pdf:
      image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
      ports:
        - '127.0.0.1:8480:8080'
      volumes:
        - trainingdata:/usr/share/tessdata # Required for extra OCR languages
        - ./configs:/configs
        - customfiles:/customFiles/
        - logs:/logs/
        - pipelines:/pipeline/
      environment:
        - DISABLE_ADDITIONAL_FEATURES=true
        - LANGS=it_IT

volumes:
  logs:
  pipelines:
  trainingdata:
  customfiles:
