system:
  defaultLocale: it-IT # set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # set to enable functionality which might need more testing before it fully goes live (this feature might make no changes)
  showUpdate: false # see when a new update is available
  enableAnalytics: false
ui:
  appName: 'PDF Magic' # application's visible name
  homeDescription: '' # short description or tagline shown on the homepage
  appNameNavbar: 'PDF Magic' # name displayed on the navigation bar
  languages: [it_IT] # If empty, all languages are enabled. To display only German and Polish ["de_DE", "pl_PL"]. British English is always enabled.
endpoints:
  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: ['LibreOffice'] # List groups to disable (e.g. ['LibreOffice'])
