ui:
  appName: 'PDF Magic' # application's visible name
  homeDescription: '' # short description or tagline shown on the homepage
  appNameNavbar: 'PDF Magic' # name displayed on the navigation bar
  languages: [it_IT] # If empty, all languages are enabled. To display only German and Polish ["de_DE", "pl_PL"]. British English is always enabled.

